apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: financeflow-account-service-run-    # generateName avoids name conflicts
  namespace: financeflow-workshop
  labels:
    app: financeflow
    tekton.dev/pipeline: financeflow-pipeline
spec:
  pipelineRef:
    name: financeflow-pipeline

  params:
    - name: repo-url
      value: https://github.com/rebontadeb/openshift-container-demo.git
    - name: revision
      value: main
    - name: service
      value: account-service
    - name: image-name
      value: financeflow-account
    - name: image-tag
      value: "v1.0"    # replace with $(git rev-parse --short HEAD) in CI

  workspaces:
    - name: source
      persistentVolumeClaim:
        claimName: pipeline-source

  serviceAccountName: financeflow-cicd    # from Chapter 4 — has deploy permissions
