apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pipeline-source
  namespace: financeflow-workshop
  labels:
    app: financeflow
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
