FROM nginx:1.25-alpine

COPY --chown=1001:0 nginx.conf /etc/nginx/conf.d/default.conf
COPY --chown=1001:0 index.html app.js style.css /usr/share/nginx/html/

RUN sed -i '/^user /d' /etc/nginx/nginx.conf && \
    mkdir -p /var/cache/nginx/client_temp \
             /var/cache/nginx/proxy_temp \
             /var/cache/nginx/fastcgi_temp \
             /var/cache/nginx/uwsgi_temp \
             /var/cache/nginx/scgi_temp && \
    touch /var/run/nginx.pid && \
    chown -R 1001:0 /var/cache/nginx \
                    /var/log/nginx \
                    /var/run/nginx.pid \
                    /usr/share/nginx/html \
                    /etc/nginx/conf.d && \
    chmod -R g+rwx  /var/cache/nginx \
                    /var/log/nginx \
                    /usr/share/nginx/html \
                    /etc/nginx/conf.d && \
    chmod g+rw /var/run/nginx.pid

USER 1001

EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]
