apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: account-service
  namespace: financeflow-workshop
  labels:
    app: financeflow
spec:
  selector:
    matchLabels:
      tier: account-service
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
