apiVersion: v1
kind: ConfigMap
metadata:
  name: transaction-service-config
  namespace: financeflow-workshop
  labels:
    app: financeflow
    tier: transaction-service
data:
  DB_HOST:             postgres
  DB_PORT:             "5432"
  DB_NAME:             financeflow
  ACCOUNT_SERVICE_URL: http://account-service:8080   # inter-service call
  PORT:                "8080"
  OTEL_EXPORTER_OTLP_ENDPOINT: http://financeflow-collector:4317
  OTEL_SERVICE_NAME:           transaction-service
  OTEL_PROPAGATORS:            tracecontext,baggage
