apiVersion: v1
kind: ConfigMap
metadata:
  name: account-service-config
  namespace: financeflow-workshop
  labels:
    app: financeflow
    tier: account-service
data:
  DB_HOST: postgres          # resolves via Kubernetes DNS: postgres.<namespace>.svc.cluster.local
  DB_PORT: "5432"
  DB_NAME: financeflow
  PORT:    "8080"
  OTEL_EXPORTER_OTLP_ENDPOINT: http://financeflow-collector:4317
  OTEL_SERVICE_NAME:           account-service
  OTEL_PROPAGATORS:            tracecontext,baggage
