apiVersion: v1
kind: Service
metadata:
  name: portal
  namespace: financeflow-workshop
  labels:
    app: financeflow
    tier: portal
spec:
  selector:
    tier: portal
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
