apiVersion: v1
kind: Service
metadata:
  name: transaction-service
  namespace: financeflow-workshop
  labels:
    app: financeflow
    tier: transaction-service
spec:
  selector:
    tier: transaction-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
