apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: financeflow-workshop
  labels:
    app: financeflow
    tier: database
spec:
  selector:
    tier: database
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  type: ClusterIP
